# ML Training Config - Flow Matching Model v5
# EOF-Native Retraining with Variance Head from Epoch 0
batch_size: 4
learning_rate: 5e-5
epochs: 1000
output_dir: ml_output_flow5
mixed_precision: fp16
num_workers: 1
data_dir: /scratch/11353/afahad/geossub/geos_subc/dataprocess/
train_start_year: 1999
train_end_year: 2000
val_start_year: 2021
val_end_year: 2022
preload: True
save_top_k: 4

reset_validation_history: False
