# ML Training Config - Custom Diffusion Model v5
batch_size: 4
learning_rate: 5e-5
epochs: 1000
output_dir: ml_output_diffusion_v5
mixed_precision: fp16
num_workers: 1
data_dir: /home1/11353/afahad/geos_subc/dataprocess
train_start_year: 1999
train_end_year: 2014
val_start_year: 2015
val_end_year: 2016
preload: True
save_top_k: 4
