# ML Training Config - Custom Flow Matching Model v6
batch_size: 4
learning_rate: 1e-5
epochs: 1000
output_dir: ml_output_flow4
mixed_precision: fp16
num_workers: 1
data_dir: /home1/11353/afahad/geos_subc/dataprocess
train_start_year: 1999
train_end_year: 2020
val_start_year: 2021
val_end_year: 2022
preload: False
save_top_k: 4
reset_validation_history: True
