name: geossub_env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - mamba
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - xarray
  - zarr
  - pandas
  - netcdf4
  - dask
  - matplotlib
  - cartopy
  - seaborn
  - tqdm
  - pip
  - pip:
      - arraylake
      - icechunk
      - diffusers
      - accelerate
      - requests
