"""
MJO Wave Weekly Means Processing Script
=======================================
Processes the daily isolated MJO Wave spatial map into weekly-mean Zarr files
aligned with GEOS S2S3 initialization dates.

Data Source: mjo_wave_spatial_1999_2022.zarr (Generated by extract_mjo_wave.py)
Output: mjo_wave_weekly_{year}.zarr with dims (S, L, Y, X) 

For each GEOS init date (S dimension), we compute 4 weekly means of the
MJO Wave leading up to the forecast start:
    L=0 → Week -4: [S-28, S-22]  (oldest)
    L=1 → Week -3: [S-21, S-15]
    L=2 → Week -2: [S-14, S-8]
    L=3 → Week -1: [S-7,  S-1]   (most recent)

Usage:
    python dataprocess/process_mjowave.py
    python dataprocess/process_mjowave.py --years 1999 2000
"""
import xarray as xr
import numpy as np
import pandas as pd
import os
import glob
from tqdm import tqdm
import argparse


# --- Configuration ---
MJO_FILE = "dataprocess/mjo_wave_spatial_1999_2022.zarr"
GEOS_DIR = "dataprocess"
OUTPUT_DIR = "dataprocess"


def process_year(year, ds_mjo_full, output_dir=OUTPUT_DIR):
    """
    Process MJO Wave data for one year:
    1. Load GEOS Zarr to get init dates and target grid
    2. Slice MJO daily data for needed time window (current + previous year)
    3. Compute 4 weekly means before each init date
    4. Save as Zarr
    """
    out_path = os.path.join(output_dir, f"mjo_wave_weekly_{year}.zarr")
    if os.path.exists(out_path):
        print(f"File {out_path} already exists. Skipping {year}.")
        return

    # 1. Load GEOS to get init dates and grid
    geos_path = os.path.join(GEOS_DIR, f"geos_subc_{year}.zarr")
    if not os.path.exists(geos_path):
        print(f"GEOS file not found: {geos_path}. Skipping {year}.")
        return
    
    ds_geos = xr.open_zarr(geos_path, consolidated=False)
    
    if 'S' not in ds_geos.dims:
        print(f"Dimension 'S' not found in {geos_path}. Skipping.")
        return
    
    init_dates = pd.to_datetime(ds_geos['S'].values)
    target_lat = ds_geos.coords['Y'] if 'Y' in ds_geos.coords else ds_geos.coords['lat']
    target_lon = ds_geos.coords['X'] if 'X' in ds_geos.coords else ds_geos.coords['lon']
    
    print(f"\n{'='*60}")
    print(f"Processing MJO Wave for {year}")
    print(f"  GEOS init dates: {len(init_dates)} ({init_dates[0].date()} → {init_dates[-1].date()})")
    print(f"  Target grid: {len(target_lat)} × {len(target_lon)}")
    
    # 2. Slice MJO data for the needed time window
    # We need data from Dec of the previous year up to the end of the current year
    start_date = f"{year-1}-12-01"
    end_date = f"{year}-12-31"
    
    try:
        ds_mjo_slice = ds_mjo_full.sel(time=slice(start_date, end_date))
    except Exception as e:
        print(f"  Error slicing MJO data for {year}: {e}")
        return
        
    if len(ds_mjo_slice.time) == 0:
        print(f"  No MJO data found for {year} in the archive file. Skipping.")
        return
        
    print(f"  Loading 13-month slice into RAM for fast access...")
    da_mjo = ds_mjo_slice['mjo_wave'].compute()
    
    # Ensure dimensions match GEOS target names immediately to prevent concat errors
    lat_name_mjo = 'lat' if 'lat' in da_mjo.coords else 'latitude'
    lon_name_mjo = 'lon' if 'lon' in da_mjo.coords else 'longitude'
    da_mjo = da_mjo.rename({lat_name_mjo: target_lat.name, lon_name_mjo: target_lon.name})
    
    # 3. Compute 4 weekly means BEFORE each init date
    print(f"  Computing 4-weekly observed means for {len(init_dates)} init dates...")
    
    processed_data = []
    skipped = 0
    
    for init_date in tqdm(init_dates, desc=f"  MJO Output {year}"):
        weeks = []
        valid = True
        
        for w in range(4):
            w_end = init_date - pd.Timedelta(days=(3 - w) * 7 + 1)
            w_start = w_end - pd.Timedelta(days=6)
            
            try:
                # Need to use inclusive slicing for xarray datetime
                chunk = da_mjo.sel(time=slice(w_start, w_end))
                # For daily data, a full week should have 7 days
                if len(chunk.time) < 1:
                    # Missing data for this week (e.g. 1998 data requested but we only have 1999+)
                    # Append NaN block so the shape is maintained
                    nan_week = xr.DataArray(
                        np.full((len(target_lat), len(target_lon)), np.nan, dtype=np.float32),
                        dims=[target_lat.name, target_lon.name],
                        coords={target_lat.name: target_lat, target_lon.name: target_lon}
                    )
                    weeks.append(nan_week)
                else:
                    # Compute mean over the available days in the week
                    w_mean = chunk.mean(dim='time').squeeze()
                    weeks.append(w_mean)
            except Exception:
                # Fallback NaN block if slicing completely fails
                nan_week = xr.DataArray(
                    np.full((len(target_lat), len(target_lon)), np.nan, dtype=np.float32),
                    dims=[target_lat.name, target_lon.name],
                    coords={target_lat.name: target_lat, target_lon.name: target_lon}
                )
                weeks.append(nan_week)
        
        # We always have 4 elements in weeks now (some might be NaN)
        # We don't skip the init date just because 1 week is missing. GEOS handles NaNs.
        
        # Stack the 4 weeks along a new 'L' dimension
        sample = xr.concat(weeks, dim='L')
        sample = sample.assign_coords(L=np.arange(4))
        
        processed_data.append(sample)
    
    if skipped > 0:
        print(f"  Warning: {skipped}/{len(init_dates)} dates had missing MJO data (filled NaN)")
    
    # 4. Stack and save as Zarr
    if len(processed_data) > 0:
        ds_out = xr.concat(processed_data, dim='S')
        ds_out = ds_out.assign_coords(S=init_dates)
        
        # Format as dataset with standard attributes
        ds_final = ds_out.to_dataset(name='mjo_wave')
        ds_final['mjo_wave'].attrs = {
            'units': 'W/m2 Anomaly',
            'long_name': 'MJO Wave Spatial Envelope (Weekly Mean)',
            'description': '4-week trailing means before GEOS S2S init dates',
            'source': 'NOAA PSL OLR (Wheeler-Kiladis filtered)'
        }
        
        out_path = os.path.join(output_dir, f"mjowave_weekly_{year}.zarr")
        print(f"  Saving to {out_path}...")
        
        import dask
        with dask.config.set(scheduler='synchronous'):
            ds_final.to_zarr(out_path, mode='w')
        
        print(f"  ✓ Finished {year}: {out_path}")
        print(f"    Shape: (S={len(init_dates)}, L=4, Y={len(target_lat)}, X={len(target_lon)})")
    
    ds_geos.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Process MJO Wave Spatial Map → GEOS weekly Zarr")
    parser.add_argument("--years", type=int, nargs="+", default=None,
                        help="Specific years to process. Default: 1999-2016")
    args = parser.parse_args()
    
    mjo_files = sorted(glob.glob("dataprocess/mjo_wave_spatial_*.zarr"))
    if not mjo_files:
        print("ERROR: No base MJO files found (dataprocess/mjo_wave_spatial_*.zarr)")
        print("Please run `python dataprocess/extract_mjo_wave.py` first to generate the daily spatial maps.")
        exit(1)
        
    print(f"Loading {len(mjo_files)} continuous MJO wave datasets...")
    ds_list = [xr.open_zarr(f, consolidated=False) for f in mjo_files]
    ds_mjo_full = xr.concat(ds_list, dim='time').sortby('time')
    
    print(f"  Time range: {ds_mjo_full.time.values[0]} to {ds_mjo_full.time.values[-1]}")
    
    years = args.years if args.years else list(range(1999, 2026))
    
    print(f"Processing MJO into weekly means for years: {years}")
    for year in years:
        process_year(year, ds_mjo_full)
    
    ds_mjo_full.close()
    print(f"\nAll done! MJO weekly files saved to {OUTPUT_DIR}/")
